<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Boletín</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
  td {
    border: 1.5px solid black;
  }
  table {
    border-collapse: collapse;
    border-spacing: 0;
    margin-top: 15px;
    width: 100%;
    page-break-inside: avoid;
  }
  .datos{
    padding-left: 15px;
    font-size: 17px;
  }
  </style>
</head>
<body>
  <h2>
    Boletines <?= $estudiantes[0]['curso'] ?>° de Secundaria, Paralelo <?= $estudiantes[0]['paralelo'] ?>
  </h2>
  <?php
    foreach($estudiantes as $estudiante):
  ?>
  <table>
    <tr>
      <td class="datos" colspan="7">
        <h5 class="center">San Sebasti&aacute;n "B"</h5>
        <p><b>Nombre: </b><?= $estudiante['nombre'] ?></p>
        <p><b>Curso: </b><?= $estudiante['curso'] ?>° de Secundaria, paralelo <?= $estudiante['paralelo'] ?></p>
      </td>
    </tr>
    <tr>
      <td><b>Campos Saberes y Conocimientos</b></td>
      <td><b>&Aacute;REAS CURRICULARES</b></td>
      <td><b>Primer Bimestre</b></td>
      <td><b>Segundo Bimestre</b></td>
      <td><b>Tercer Bimestre</b></td>
      <td><b>Cuarto Bimestre</b></td>
      <td><b>NOTA FINAL</b></td>
    </tr>
    <?php
      $campo = $estudiante['notas'][0]['campo'];
      $array = [];
      $cont = 0;
      foreach($estudiante['notas'] as $nota):
        if ($nota['campo'] != $campo) {
          array_push($array, $cont);
          $campo = $nota['campo'];
          $cont = 1;
        } else {
          $cont++;
        }
      endforeach;
      array_push($array, $cont);
    ?>
    <?php
      $campo = 'narana';
      $cont = 0;
      $nroMat = count($estudiante['notas']);
      $sum1Bim = 0;
      $sum2Bim = 0;
      $sum3Bim = 0;
      $sum4Bim = 0;
      $sumFinal = 0;
      foreach($estudiante['notas'] as $nota):
    ?>
    <tr>
      <?php
        if($nota['campo'] != $campo) {
          echo '<td rowspan="'.$array[$cont].'">' . $nota['campo'] . '</td>';
          $campo = $nota['campo'];
          $cont++;
        }
        $final = round((intval($nota['bim1'])+intval($nota['bim2'])+intval($nota['bim3'])+intval($nota['bim4']))/4);
        $sum1Bim += $nota['bim1'];
        $sum2Bim += $nota['bim2'];
        $sum3Bim += $nota['bim3'];
        $sum4Bim += $nota['bim4'];
        $sumFinal += $final;
      ?>
      <td><?= $nota['nombre'] ?></td>
      <td><?= $nota['bim1'] ?></td>
      <td><?= $nota['bim2'] ?></td>
      <td><?= $nota['bim3'] ?></td>
      <td><?= $nota['bim4'] ?></td>
      <td><b><?= $final ?></b></td>
    </tr>
    <?php
      endforeach;
    ?>
    <tr>
      <td colspan="2">PROMEDIOS</td>
      <td><?= round($sum1Bim/$nroMat, 2) ?></td>
      <td><?= round($sum2Bim/$nroMat, 2) ?></td>
      <td><?= round($sum3Bim/$nroMat, 2) ?></td>
      <td><?= round($sum4Bim/$nroMat, 2) ?></td>
      <td><?= round($sumFinal/$nroMat, 2) ?></td>
    </tr>
  </table>
  <br>
  <br>
  <?php
    endforeach;
  ?>
</body>
</html>