<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Boletín</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
  td {
    border: 1.5px solid black;
  }
  table {
    border-collapse: collapse;
    border-spacing: 0;
  }
  .datos{
    padding-left: 15px;
    font-size: 20px;
  }
  </style>
</head>
<body>
  <?php
    foreach($estudiantes as $estudiante):
  ?>
  <table>
    <tr>
      <td class="datos" colspan="7">
        <h4 class="center">San Sebasti&aacute;n "B"</h4>
        <p><b>Nombre: </b><?= $estudiante['nombre'] ?></p>
        <p><b>Curso: </b><?= $estudiante['curso'] ?>° de Secundaria, paralelo <?= $estudiante['paralelo'] ?></p>
      </td>
    </tr>
    <tr>
      <td>Campos Saberes y Conocimientos</td>
      <td>&Aacute;REAS CURRICULARES</td>
      <td>Primer Bimestre</td>
      <td>Segundo Bimestre</td>
      <td>Tercer Bimestre</td>
      <td>Cuarto Bimestre</td>
      <td>NOTA FINAL</td>
    </tr>
    <?php
      foreach($estudiante['notas'] as $nota):
    ?>
    <tr>
      <td><?= $nota['campo'] ?></td>
      <td><?= $nota['nombre'] ?></td>
      <td><?= $nota['bim1'] ?></td>
      <td><?= $nota['bim2'] ?></td>
      <td><?= $nota['bim3'] ?></td>
      <td><?= $nota['bim4'] ?></td>
      <td>promedio</td>
    </tr>
    <?php
      endforeach;
    ?>
<!--     <tr>
      <td rowspan="6">COMUNIDAD Y SOCIEDAD</td>
      <td>Comunicaci&oacute;n y Lenguajes</td>
      <td>80</td>
      <td>80</td>
      <td>50</td>
      <td>20</td>
      <td>55</td>
    </tr>
    <tr>
      <td>Lengua Extranjera</td>
      <td>50</td>
      <td>60</td>
      <td>70</td>
      <td>80</td>
      <td>65</td>
    </tr>
    <tr>
      <td>Ciencias Sociales</td>
      <td>70</td>
      <td>70</td>
      <td>70</td>
      <td>70</td>
      <td>70</td>
    </tr>
    <tr>
      <td>Educaci&oacute;n F&iacute;sica y Deportes</td>
      <td>60</td>
      <td>60</td>
      <td>60</td>
      <td>60</td>
      <td>60</td>
    </tr>
    <tr>
      <td>Educaci&oacute;n Musical</td>
      <td>65</td>
      <td>65</td>
      <td>65</td>
      <td>65</td>
      <td>65</td>
    </tr>
    <tr>
      <td>Artes Pl&aacute;stica y Visuales</td>
      <td>70</td>
      <td>70</td>
      <td>70</td>
      <td>70</td>
      <td>70</td>
    </tr>
    <tr>
      <td rowspan="2">CIENCIA TECNOLOG&Iacute;A Y PRODUCCI&Oacute;N</td>
      <td>Matem&aacute;tica</td>
      <td>75</td>
      <td>75</td>
      <td>75</td>
      <td>75</td>
      <td>75</td>
    </tr>
    <tr>
      <td>T&eacute;cnica Tecnol&oacute;gica</td>
      <td>70</td>
      <td>70</td>
      <td>70</td>
      <td>70</td>
      <td>70</td>
    </tr>
    <tr>
      <td rowspan="2">VIDA TIERRA Y TERRITORIO</td>
      <td>Biolog&iacute;a - Geogr&aacute;fica</td>
      <td>80</td>
      <td>80</td>
      <td>80</td>
      <td>80</td>
      <td>80</td>
    </tr>
    <tr>
      <td>F&iacute;sica - Qu&iacute;mica</td>
      <td>85</td>
      <td>85</td>
      <td>85</td>
      <td>85</td>
      <td>85</td>
    </tr>
    <tr>
      <td rowspan="2">COSMOS Y PENSAMIENTO</td>
      <td>Filosof&iacute;a</td>
      <td>90</td>
      <td>90</td>
      <td>90</td>
      <td>90</td>
      <td>90</td>
    </tr>
    <tr>
      <td>Valores Espiritualidades y Religiones</td>
      <td>95</td>
      <td>95</td>
      <td>95</td>
      <td>95</td>
      <td>95</td>
    </tr> -->
    <tr>
      <td colspan="2">PROMEDIOS</td>
      <td>80</td>
      <td>80</td>
      <td>80</td>
      <td>80</td>
      <td>80</td>
    </tr>
  </table>
  <br>
  <br>
  <?php
    endforeach;
  ?>
</body>
</html>