<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Docentes</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      width: 231mm;
      padding: 2cm;
    }

    header {
      border: 1.2px solid #424242;
      border-radius: 11px;
      padding: 10px;
    }

    .title {
      text-align: center;
    }

    .header-data-container div {
      display: inline;
    }

    .header-data-container {
      display: flex;
      justify-content: space-around;
    }

    table {
      color: #333;
      font-family: Helvetica, Arial, sans-serif;
      width: 640px;
      border-collapse: collapse;
      border-spacing: 0;
      margin: 15px auto;
    }
    td,
    th {
      height: 30px;
      border: 2px solid transparent;
    }
    th {
      background: #DFDFDF;
      font-weight: bold;
    }
    td {
      background: #FAFAFA;
      text-align: left;
      padding-left: 5px;
    }
    tr:nth-child(even) td {
      background: #F1F1F1;
    }
    tr:nth-child(odd) td {
      background: #FEFEFE;
    }
  </style>
</head>

<body>
  <header>
    <h2 class="title">Lista Docentes</h2>
    <h4 class="title">San Sebastián B</h4>
    <div class="header-data-container">
      <div>
        <b>Fecha:</b>
        <span><?= date('d-m-Y') ?></span>
      </div>
      <div>
        <b>Hora:</b>
        <span><?= date('H:i:s') ?></span>
      </div>
    </div>
  </header>
  <br />
  <table>
    <tr>
      <th>Nro</th>
      <th>Nombre</th>
      <th>C.I.</th>
    </tr>
    <?php
      $cont = 1;
      foreach($docentes as $docente):
    ?>
    <tr>
      <td><?= $cont ?></td>
      <td><?= $docente->appat.' '.$docente->apmat.' '.$docente->nombres ?></td>
      <td><?= $docente->ci ?></td>
    </tr>
    <?php
      $cont++;
      endforeach;
    ?>
  </table>
</body>

</html>